const MEMCACHED_HOST='localhost';
const MEMCACHED_PORT='11211';
const BACKEND_HOST='localhost';
const BACKEND_PORT='3000';

module.exports = { MEMCACHED_HOST, MEMCACHED_PORT,BACKEND_HOST,BACKEND_PORT};